### ISSUE TITLE
Error in report.rmd

### ISSUE THREAD

**Issue by monicazhu** [yuucao/1019#1]
There is an error when I tried to `make` the report. The error message is as follows:

Quitting from lines 29-32 (report.Rmd) 
Error: 'D:/22fall/INFO550/Final/BRCA.csv' does not exist.

Execution halted
make: *** [report.html] Error 1

I think you may need to use a relative path file instead of an absolute file path in report.rmd.

**Comment by yuucao** [comment]
Thanks, I've modified this.
